db:
  username: postgres
  password: pass
  pool:
    size: 12
    timeout: 10
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1

logging:
  level:
    org.springframework.jdbc.core: TRACE
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true2
      hbm2ddl.auto: update